name: "CI"
on:
  pull_request:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Run tests
        run: npm run test:ci
